# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IC6w41Gdse14VXLZRAPntDuNVYGS93NL
"""

import numpy as np

a=np.random.randint(30,99,20)
a

a[-1]

a[4]

a.ndim

b=np.random.randint(20,80,(8,9))
b



b.shape

b[1:5,1:6]

import pandas as pd

k=[[4,7],[2,1],[7,3],[90,50]]
k

t=np.array(k)
t

t.ndim

pd.Series(k)

pd.DataFrame(t)

df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

df.columns

df['sub']

df['sub'].mean()

df['sub'].median()

df['sub'].var()

df['sub'].std()

df['sub'].min()

df['sub'].max()

df['sub'].quantile(0.25)